package com.speakbetter.practice.service.storage;

import com.speakbetter.practice.service.StoredFile;
import java.time.LocalDateTime;
import org.springframework.web.multipart.MultipartFile;

/**
 * Persists and retrieves recording video bytes. Two implementations exist:
 * {@link LocalFilesystemRecordingStorage} (default, used for local development)
 * and {@link CloudflareR2RecordingStorage} (active under the "r2" profile, used
 * in deployment where the filesystem isn't persistent). Filenames are always
 * generated by the implementation - the browser-supplied filename is never
 * trusted or used to build a storage key.
 */
public interface RecordingStorage {

	StoredFile store(MultipartFile file, LocalDateTime recordedAt);

	VideoSource loadVideo(String key);

	void delete(String key);
}
